[app]
name = "douyin"

[app.http]
host = "127.0.0.1"
port = "8080"

[app.grpc]
host = "127.0.0.1"
port = "8505"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "root"
database = "dou_sheng"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"